### ISSUE TITLE
ionic 3 -- not working 

### ISSUE THREAD

**Issue by jehadja** [sarriaroman/photoviewer#105]
hello , thanks for this plugin unfortunately  it didn't work with the last version of Ionic 3 
recreate bug 
1- 
```
$ ionic cordova plugin add com-sarriaroman-photoviewer
     $ npm install --save @ionic-native/photo-viewer 
```
2- 
import { PhotoViewer } from '@ionic-native/photo-viewer';
  imports: [
PhotoViewer
]
 3-BUG 
```
 Error: Unexpected value 'PhotoViewer' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:8100/build/vendor.js:81942:34)
    at http://localhost:8100/build/vendor.js:96564:44
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/vendor.js:96547:49)
    at JitCompiler._loadModules (http://localhost:8100/build/vendor.js:114960:87)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:114921:36)
    at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:114837:37)
    at CompilerImpl.compileModuleAsync (http://localhost:8100/build/vendor.js:80778:49)
    at PlatformRef.bootstrapModule (http://localhost:8100/build/vendor.js:5797:25)
    at Object.227 (http://localhost:8100/build/main.js:1242:109)
```
thank for help 
 for me i will use it directly with cordova hope you will find problem soon 👍

**Comment by jehadja** [comment]
imports: [
PhotoViewer
]
/// 
i miss add it on provider
