### ISSUE TITLE
Ionic app crashes on Android when tapping the share button in PhotoViewer

### ISSUE THREAD

**Issue by honrust** [sarriaroman/photoviewer#124]
In my Ionic2 app, I integrated PhotoViewer v1.1.16. I can use the plugin to view my photos, but as soon as I press the Share button, the app crashes.

Samsung S8, Android 8.0.0

Here is the stacktrace from logcat:

```
05-10 14:18:57.852 25022 25022 D skia    : Encode PNG Singlethread processname=nl.flusso.mobile.ad6.v2 :     676991 us, width=1080, height=718
05-10 14:18:57.854 25022 25022 D AndroidRuntime: Shutting down VM
05-10 14:18:57.859 25022 25022 E AndroidRuntime: FATAL EXCEPTION: main
05-10 14:18:57.859 25022 25022 E AndroidRuntime: Process: nl.flusso.mobile.ad6.v2, PID: 25022
05-10 14:18:57.859 25022 25022 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Download/share_image_1525954737169.png exposed beyond app through ClipData.Item.getUri()
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.net.Uri.checkFileUriExposed(Uri.java:2348)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:944)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:10480)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:10486)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:10465)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4564)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4522)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4883)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4851)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at com.sarriaroman.PhotoViewer.PhotoActivity$2.onClick(PhotoActivity.java:104)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.view.View.performClick(View.java:6891)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26083)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6938)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
05-10 14:18:57.859 25022 25022 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
05-10 14:18:57.860 25022 25022 E UncaughtException:
05-10 14:18:57.860 25022 25022 E UncaughtException: android.os.FileUriExposedException: file:///storage/emulated/0/Download/share_image_1525954737169.png exposed beyond app through ClipData.Item.getUri()

05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.net.Uri.checkFileUriExposed(Uri.java:2348)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.content.ClipData.prepareToLeaveProcess(ClipData.java:944)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.content.Intent.prepareToLeaveProcess(Intent.java:10480)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.content.Intent.prepareToLeaveProcess(Intent.java:10486)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.content.Intent.prepareToLeaveProcess(Intent.java:10465)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.app.Activity.startActivityForResult(Activity.java:4564)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.app.Activity.startActivityForResult(Activity.java:4522)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.app.Activity.startActivity(Activity.java:4883)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.app.Activity.startActivity(Activity.java:4851)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at com.sarriaroman.PhotoViewer.PhotoActivity$2.onClick(PhotoActivity.java:104)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.view.View.performClick(View.java:6891)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.view.View$PerformClick.run(View.java:26083)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.os.Handler.handleCallback(Handler.java:789)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.os.Handler.dispatchMessage(Handler.java:98)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.os.Looper.loop(Looper.java:164)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at android.app.ActivityThread.main(ActivityThread.java:6938)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at java.lang.reflect.Method.invoke(Native Method)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
05-10 14:18:57.860 25022 25022 E UncaughtException:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
005-10 14:18:57.871 25022 25027 I zygote64: After code cache collection, code=243KB, data=153KB

```

**Comment by karimwarp** [comment]
getting the same error, but mine crushes if you tap share before image is loaded. Am using a website url

**Comment by nginx17** [comment]
any update ? same issue

**Comment by mirko77** [comment]
On Android 8.0, tapping the share button does nothing, but the app does not crash in my case

The close button works as expected

**Comment by sarriaroman** [comment]
Solved with https://github.com/sarriaroman/photoviewer/pull/125
