### ISSUE TITLE
Error loading big picture on Android - Permission denied

### ISSUE THREAD

**Issue by Michka2003** [sarriaroman/photoviewer#145]
Hello
I'm facing the following error with big picture (400k in base64).
* Issue is not present on iOS.
* with smaller pictures, the plugin shows correctly the picture
* problem is present on Android 7 and Android 8.1
* this issue appeared after updating to v1.1.18 (the problem is not present on version v1.1.10)
Here below the logs.

[big_picture_400k.txt](https://github.com/sarriaroman/photoviewer/files/2384149/big_picture_400k.txt)

Thanks in advance

W/PluginManager: THREAD WARNING: exec() call to PhotoViewer.show blocked the main thread for 34ms. Plugin should use CordovaInterface.getThreadPool().
D/InputMethodManager: HSI from window - flag : 0 Pid : 16221
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Download/share_image_1536942033097.png (Permission denied)
                  at java.io.FileOutputStream.open(Native Method)
                  at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
                  at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
                  at com.sarriaroman.PhotoViewer.PhotoActivity.getLocalBitmapFileFromString(PhotoActivity.java:233)
                  at com.sarriaroman.PhotoViewer.PhotoActivity$4.doInBackground(PhotoActivity.java:187)
                  at com.sarriaroman.PhotoViewer.PhotoActivity$4.doInBackground(PhotoActivity.java:183)
                  at android.os.AsyncTask$2.call(AsyncTask.java:304)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                  at java.lang.Thread.run(Thread.java:762)
D/ViewRootImpl@ae0034[PhotoActivity]: ThreadedRenderer.create() translucent=false
D/InputTransport: Input channel constructed: fd=94
D/ViewRootImpl@ae0034[PhotoActivity]: setView = DecorView@a5e1e5d[PhotoActivity] touchMode=true
D/ViewRootImpl@ae0034[PhotoActivity]: dispatchAttachedToWindow
D/ViewRootImpl@ae0034[PhotoActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1920,1200] result=0x27 surface={isValid=true -1093668864} surfaceGenerationChanged=true
D/ViewRootImpl@ae0034[PhotoActivity]: mHardwareRenderer.initialize() mSurface={isValid=true -1093668864} hwInitialized=true
D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1920x1200]-format:1
D/ViewRootImpl@ae0034[PhotoActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1920, 1200) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 36 - 0, 0) or=2
                                      MSG_WINDOW_FOCUS_CHANGED 1
                                      mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -1093668864}
V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@3947ca3 nm : be.mobi33.mobi33v2 ic=null
I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=134
                  Input channel destroyed: fd=130
D/ViewRootImpl@ae0034[PhotoActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1920, 1200) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=2
D/ViewRootImpl@9e6703a[MainActivity]: mHardwareRenderer.destroy()#1

**Comment by Michka2003** [comment]
Solved by activating the option: **share: true** 
Then the App asks for access autorisation at first call.
Then the plugin is working fine.
my options are: { share: true, closeButton: true, copyToReference: true }
