### ISSUE TITLE
errors when cordova build android

### ISSUE THREAD

**Issue by seasonstar** [sarriaroman/photoviewer#18]
Here is the log..
`:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/yaoxingtang/Library/Android/sdk/build-tools/23.0.2/dx --dex --no-optimize --output /Users/yaoxingtang/maybi/maybi-ionic/platforms/android/build/intermediates/dex/debug --input-list=/Users/yaoxingtang/maybi/maybi-ionic/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 27.942 secs

/Users/yaoxingtang/maybi/maybi-ionic/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/yaoxingtang/maybi/maybi-ionic/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/yaoxingtang/maybi/maybi-ionic/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/yaoxingtang/maybi/maybi-ionic/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/yaoxingtang/maybi/maybi-ionic/platforms/android/cordova/build: Command failed with exit code 1`

Help

**Comment by tumispro** [comment]
Any fix or alternative plugin for this?

**Comment by sarriaroman** [comment]
This is not a problem with the plugin. Here is the solution: https://developer.android.com/studio/build/multidex.html

**Comment by tumispro** [comment]
You're absolutely correct. Thanks!
