### ISSUE TITLE
Android app crashes on share button press

### ISSUE THREAD

**Issue by typeoneerror** [sarriaroman/photoviewer#209]
Works on iOS, but not on Android.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.precisionnutrition.pncoaching, PID: 31222
    java.lang.NullPointerException: file
        at android.net.Uri.fromFile(Uri.java:473)
        at com.sarriaroman.PhotoViewer.PhotoActivity$2.onClick(PhotoActivity.java:124)
        at android.view.View.performClick(View.java:7870)
        at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29363)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by loris-benoit** [comment]
Got the same issue, let me know if you find a workaround :)

**Comment by CeloGomesBR** [comment]
I have the same problem... :(

**Comment by rolinger** [comment]
same here....crashes on share button every time.  Have to disable for now.
