### ISSUE TITLE
Conflict with Native Transitions plugin (Android)

### ISSUE THREAD

**Issue by arivanbastos** [sarriaroman/photoviewer#39]
I'm using this plugin in a ionic project that uses https://github.com/shprink/ionic-native-transitions. 

After I open and close an image using Photoviewer, the first time I click on an back button in my app results in crash. If I uninstall NativePageTransitions plugin, everything goes ok.

I'm running:
Cordova CLI 6.3.1
Ionic: 1.3
Ionic cli: 2.1.0
Android 4.4.2

**Comment by sarriaroman** [comment]
Are you able to get the stack trace from Android Monitor?

**Comment by arivanbastos** [comment]
For sure:

```
10-24 17:22:23.407 30757-30757/com.virtualizesolucoes.condoclass E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.virtualizesolucoes.condoclass, PID: 30757
                                                                                   java.lang.OutOfMemoryError
                                                                                       at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
                                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
                                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
                                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:747)
                                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:727)
                                                                                       at com.telerik.plugins.nativepagetransitions.NativePageTransitions.getBitmap(NativePageTransitions.java:724)
                                                                                       at com.telerik.plugins.nativepagetransitions.NativePageTransitions.access$400(NativePageTransitions.java:27)
                                                                                       at com.telerik.plugins.nativepagetransitions.NativePageTransitions$2.run(NativePageTransitions.java:167)
                                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:146)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5603)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
10-24 17:22:24.527 30757-31481/com.virtualizesolucoes.condoclass D/FirebaseCrash: Response code: 200
```

**Comment by arivanbastos** [comment]
Seems to be related to https://github.com/sarriaroman/photoviewer/issues/38 that also triggers "Out of memory" error.
