### ISSUE TITLE
android.os.TransactionTooLargeException: data parcel size xxx bytes

### ISSUE THREAD

**Issue by kctang** [sarriaroman/photoviewer#69]
Hi,

Any idea why I am getting a lot of these exceptions show up in logcat? It does not happen all the time but when it does, this exception repeats many times.

```
03-29 21:19:22.935  1582  3109 W ActivityManager: Exception in new application when starting activity com.ionicframework.xxx/com.sarriaroman.PhotoViewer.PhotoActivity
03-29 21:19:22.935  1582  3109 W ActivityManager: android.os.TransactionTooLargeException: data parcel size 607284 bytes
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:1098)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:2562)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:1349)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:9862)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:9949)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:515)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4156)
03-29 21:19:22.935  1582  3109 W ActivityManager: 	at android.os.Binder.execTransact(Binder.java:453)

```

**Comment by kctang** [comment]
This was due to the fact that I was trying to load base64 encoded images via data:// protocol. It works for smaller images but I don't think it is a "supported" feature.
